version: '3.8'

services:
  postgres:
    container_name: postgres-odoo
    image: postgres:13-alpine # Latest postgres not support odoo 14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/odoo/
    ports:
      - 5432:5432/tcp
 
  odoo:
    container_name: odoo-frontend
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069/tcp

  nginx:
    container_name: odoo-proxy-pass
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odoo
    restart: always
    links:
      - odoo:odoo
      - pgadmin:pgadmin

volumes:
  odoo-db-data:
  odoo-web-data:
